[emsc]
# Path to the directory containing sentence files
sentences_dir=

# Path to the output directory
save_dir=

# Path to the n-gram language model
ngram_model_path

# Lambda parameter balancing path score and language model score
lambd=

# Maximum number of successor neighbor nodes to select
max_neighbors=

# Queue capacity
queue_size=
